spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cachedb
    username: cacheuser
    password: cachepass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

cache:
  maxSize: 3
